### PR TITLE
Modernize government website blog 

### PR DESCRIPTION
**Pull request by lpgoldstein**
[Preview](https://dev-blog-nrrd.app.cloud.gov/modernize-government-website/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@lpgoldstein 

Looks like there's an extra space between "audit" and the comma here:
image

The 2 wireframe images and the notification banner image are all small and blurry for me. You might want to save higher quality versions of these images. I've learned that the version of the images in the Word doc are too small. I usually create larger versions of the images specifically for the website.

Other than that, looks good!

**Comment by cthomasONRR** [comment]
@lpgoldstein 

The wireframe images are not appearing now:
image
image

**Comment by cthomasONRR** [comment]
@lpgoldstein 

I'm a little confused on the finalized wireframe image- I think what's in the preview now is an image of the live site, not the wireframe? I understand why you probably scrolled a bit over the hero image, but with it scrolled, it looks like we have an upside-down picture of mountains which is kind of distracting. The wireframe can be found here: https://qmcq5k.axshare.com/#id=e1wh3o&p=home_v3&dp=0&g=1

Otherwise everything else looks good.

**Comment by lpgoldstein** [comment]
@cthomasONRR Thanks for your careful review. Updated image. I had to clear my cache to see the update.

**Review by cthomasONRR — APPROVED** [review]
Thanks for updating. Looks good- approved!

**Comment by lpgoldstein** [comment]
@Maroyafaied ready for your review.

**Comment by lpgoldstein** [comment]
@Maroyafaied 
image
image

**Pull request merged**
