### PR TITLE
Publish Hallway Study State and OS Region Navigation blog post

### LINKED ISSUE #399: Publish state and OR navigation blog
- [x] Incorporate final edits
- [x] send to chris for comms review
- [ ] publish

### PR DESCRIPTION
**Pull request by AlexandracmONRR**
Fixes #399 
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/hallway-study-state-offshore-navigation/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
"Spring" isn't a proper noun and doesn't need to be capitalized
image

This can be "a" since MDX/Markdown does not start with a vowel. I don't think MDX is defined so might be good to do that here as well.
image

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - thank you! I've made the changes in dev.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR 

I still see the "an"... in all other instances when defining an abbreviation, you spell out the full text then put the abbreviation in parenthesis. For example, AI later on in the paragraph. I'd recommend consistency and format the MDX abbreviation the same.

image

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - agghh, sorry I got so caught up in the one fix i forgot about the other. I made the change to say, "a Multideminsional Expressions (MXD)"

**Review by cthomasONRR — APPROVED** [review]
Thanks, looks good!

**Review by lpgoldstein — APPROVED** [review]

**Pull request merged**
