### PR TITLE
content-audit-blog

### PR DESCRIPTION
**Pull request by cthomasONRR**
[Preview](https://dev-blog-nrrd.app.cloud.gov/content-audit/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@Maroyafaied @eelzi-ONRR @lpgoldstein When you have time, could you please review this blog PR? Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR Great job, I only have 2 changes. Thanks

- add the word "on" between based and page views 
image

- add the word "to" before track my progress
image

**Comment by lpgoldstein** [comment]
@cthomasONRR only two things from me: 
image use the word "noted" here instead for plain language

image

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @Maroyafaied @lpgoldstein Thank you for reviewing! I incorporated your edits into the preview. If you have time, please check again. Thanks!

**Review by eelzi-ONRR — APPROVED** [review]
@cthomasONRR Looks good!

**Review by Maroyafaied — APPROVED** [review]
Looks good!

**Pull request merged**
