### PR TITLE
change heading from DOI to ONRR

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<ISSUE NUMBER>
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR please review the heading change from Department of Interior to the Office of Natural Resources Revenue. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied looks good!

I'm wondering if we should put something in the footer saying we're part of DOI?
I know we have the DOI logo... but maybe instead of having ONRR twice in bold and in the address, we could have DOI first then ONRR once?

image

Just thinking how in the ONRR site, we have DOI up front (but not big/bolded)
image

**Comment by Maroyafaied** [comment]
@cthomasONRR I made the change in the footer but it's still building, please review once it's done. Thanks for the suggestion.

**Review by cthomasONRR — APPROVED** [review]
@Maroyafaied Looks great! Thanks!

**Comment by lpgoldstein** [comment]
@eelzi-ONRR do you have time to review? https://dev-blog-nrrd.app.cloud.gov/trusted-tester/

**Comment by eelzi-ONRR** [comment]
@lpgoldstein 

The link in the first paragraph doesn't work anymore - looks like it's been changed to this: https://www.dhs.gov/trusted-tester

Everything else looks great!

**Comment by Maroyafaied** [comment]
@lpgoldstein the first tip says "along alongside". Can you the "J" and "A" in javascript and capitalize URL? Thanks
image

**Comment by lpgoldstein** [comment]
@Maroyafaied @eelzi-ONRR updated

**Pull request merged**
