### PR TITLE
ga4-transition

### PR DESCRIPTION
**Pull request by cthomasONRR**
[Preview](https://dev-blog-nrrd.app.cloud.gov/ga4-transition/)

### CODE REVIEW

**Comment by eelzi-ONRR** [comment]
I made a couple edits in the PR - here's snippets of where I did that:
image
image
image
image
image
image

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Thanks! I made one more minor edit. 

@lpgoldstein and @AlexandracmONRR This is ready for your review.

**Comment by lpgoldstein** [comment]
@cthomasONRR The subtitles need to be in sentence case - just not fully consistent throughout blog

**Comment by lpgoldstein** [comment]
image
capitalize?

**Comment by lpgoldstein** [comment]
How about "took" instead 
image

**Comment by AlexandracmONRR** [comment]
I think that the links to each of these wiki's is a little misleading, because the link text itself implies that it is the website, not the wiki. I suggest the following text:

You can access our GA4 wiki sections to learn more: [onrr.gov wiki](https://github.com/DOI-ONRR/onrr.gov-site/wiki/GA4-Reports), [NRRD wiki](https://github.com/DOI-ONRR/nrrd/wiki/GA4-Reports), and [Blog wiki](https://github.com/DOI-ONRR/blog-nrrd/wiki/Analytics-Templates-&-Instructions).

image

**Review by lpgoldstein — APPROVED** [review]

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @lpgoldstein @AlexandracmONRR All your suggested changes are incorporated. I'm going to share with Maroya now. Thanks!

**Review by AlexandracmONRR — APPROVED** [review]
Besides my comment about the wiki links, everything looks great.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Please refresh, the updates are present. 
image

**Pull request merged**
