### PR TITLE
Dev-->Master USWDS blog 

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<ISSUE NUMBER>
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/USWDS/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @Maroyafaied One URL to our old GitHub no longer works since we switched to DOI-ONRR. It needs to be updated to "https://github.com/DOI-ONRR". I checked all the others, and this is the only one giving me a 404.
image

**Comment by cthomasONRR** [comment]
I'm not sure I've ever updated a blog while it's in dev, I'm happy to make the update!

**Comment by Maroyafaied** [comment]
@cthomasONRR Please go ahead an make the update in dev, it's the same process you just select the dev branch.

**Comment by AlexandracmONRR** [comment]
Hi all - I reviewed, checked links, and generally I think it looks good except for 2 links in the "Earn Trust" section: (1) GitHub link that Christine pointed it out previously, and (2) CircleCi link that is giving me a 404 error. 

image

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Interesting, that CircleCi link redirected for me, but I'll go and update it anyways.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR link fixed

**Review by AlexandracmONRR — COMMENTED** [review]
The content and the updated links look good! I approve.

**Pull request merged**
