### PR TITLE
add user consent blog

### PR DESCRIPTION
**Pull request by lpgoldstein**
[Preview](https://dev-blog-nrrd.app.cloud.gov/user-research-consent/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
- All our previous blog titles are sentence case. I think it will look more uniform on the homepage if you made the title sentence case.
image

- Might be good to link PRA site (https://pra.digital.gov/) here. 
- I'm also a little unsure about the term "doing good by" in relation to PRA. Since it is a law, maybe change this to be "To be in compliance with Paperwork Reduction Act requirements, ..."
- I would also find somewhere to link this, maybe embed if you add the the 'to be in compliance" language : https://github.com/DOI-ONRR/research/wiki/Doing-design-and-research-in-the-federal-government#paperwork-reduction-act-pra.
image

- Can you add a citation (link to the authoritative source) here? Also I think "institutional review board" might be a proper noun (refs: https://www.fda.gov/about-fda/center-drug-evaluation-and-research-cder/institutional-review-boards-irbs-and-protection-human-subjects-clinical-trials; https://www.gao.gov/products/gao-23-104721)
image

- Again, citation here
image

- Sources? https://danachisnell.com/about/
image

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I'm not sure what to link to for IRB since each institution has their own. I've incorporated Christine's other comments.

**Comment by cthomasONRR** [comment]
Ok here's the last of my review:

There are sections of paragraphs where a sentence is just a long list of what the user needs to do. I wonder if this should be broken out in numbered list form to emphasize how much effort the user has to go through. Like this:

> 
> The user must: 
> 
> 1. download, 
> 2. open, 
> 3. read and comprehend on their own, 
> 4. add their electronic signature, 
> 5. reattach to the email, and 
> 6. send it back to us. 

image

image

**Comment by eelzi-ONRR** [comment]
@lpgoldstein we shouldn't link to anything for IRB. It's too complicated - there's no single IRB site except a confusing login page

**Pull request merged**
