### PR TITLE
Create USWDS blog post & add Erin & Alex to author file

### PR DESCRIPTION
**Pull request by eelzi-ONRR**
Fixes #<199>
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/USWDS/)

- [ ] Added a the USWDS blog post
- [ ] Added Erin and Alex to the author file
- [ ] Added Erin & Alex's headshots

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Here are some typos I found:

image
- Remove the space between the ] and ( to make the hyperlink work
- Add a space after (ONRR) 

image
- Remove the space between (IDEA) and . 

image
- Maybe just keep the definitions in " quotes " instead of the quote formatting? That might be simpler to read.

image
-  Looks like the list format didn't work. I've seen this before, you have to remove the Microsoft word bullets and do markdown style with just the " - " for the bullet.
- The "Vue Testing Library" link is the same as the "ES Lint" link

image
- Remove the space between the ] and ( to make the hyperlink work
- Add a comma after "At ODDD,"

image
- Remove the space between the ] and ( to make the hyperlink work

image
- Remove the space between the ] and ( to make the hyperlink work

**Comment by eelzi-ONRR** [comment]
Thanks @cthomasONRR ! Here's what I found too - we mostly found the same issues

**Throughout**
Improve display of principle defintions and H3

**Intro**
Need to fix USWDS hyperlink in first sentence
Check spacing between (ONRR) and "continues" at end of first paragraph

**start with user needs** 
Check on the file/image that's not loading.  There shouldn't be an image there at all
One instance of onrr.gov that's not hyperlinked

**Earn Trust**
Check this sentence for spacing after links: We also use the GitHub wikiand the ODDD blog to share our processes.
Automated testing tools should display as a list: For automated testing, we use: o ESLint - Code syntax and formatting o Vue Testing Library - Vue testing library o puppeteer - End to End testing o lighthouse - Performance and Accessibility testing

**embrace accessibility**
Fix section 508 hyperlink 
Fix section 508 coordinator hyperlink

**listen**
fix bugcrowd hyperlink

**Comment by eelzi-ONRR** [comment]
@cthomasONRR @Maroyafaied I've made a few rounds of edits and the blog post is ready to review now

https://dev-blog-nrrd.app.cloud.gov/USWDS/

Thanks!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Looks great! 

You can link the user types blog that just published here:
image

@Maroyafaied Can we also use this PR to update the following title? I want to make onrr.gov consistent and lower case throughout all titles.
image

**Comment by Maroyafaied** [comment]
@cthomasONRR yes, you can make that edit in this PR. Let me know if you need me to do it. @eelzi-ONRR I haven't read this yet but it's on my to do list.

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @cthomasONRR I made content changed in the section talking about Bugcrowd to explain that it's an account for our VDP. Sorry, I didn't make that clear early on, you can see my changes in the pic below. Feel free to correct any grammer. The only other thing I noticed is that sometimes GitHub is spelled with a capital H and sometimes with lowercase, I'm not sure which is the right way but we should be consistent. 
image

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @cthomasONRR I linked to the new peronas blog posts and chnaged all the incorrect instance of GitHub. I did a final read through and I think it's ready to go

**Comment by cthomasONRR** [comment]
@eelzi-ONRR minor comments... should this be 2 sentences?

image

And I think the "S" in Section 508 should be consistently capitalized:
image
image

**Review by Maroyafaied — APPROVED** [review]

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Those changes have been made and pushed to preview

**Pull request merged**
