### PR TITLE
Matt's blog 

### PR DESCRIPTION
**Pull request by lpgoldstein**
[Preview](https://dev-blog-nrrd.app.cloud.gov/)

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@cthomasONRR do you have time to review?

**Comment by cthomasONRR** [comment]
@lpgoldstein 

- Could you go through and make the blog title and headings all sentence case? All the previous blogs have headings in sentence case.

image

- Could you link to the VSFS and ONRR websites here?

image

-  I think this should be 'agency' instead of 'department'? 

image

- Also, cite the VA group?

image

- 'Federal' doesn't need to be capitalized here 

image

- Link to these products:

image

- Link to the checklist- it's public on the wiki

image

-   Links for these as well

image

- Also, I'd recommend putting this in Hemingway and see if you can reduce reading level and simplify some sentences:

image

**Review by cthomasONRR — APPROVED** [review]
Updates look good! Approved

**Comment by Maroyafaied** [comment]
@lpgoldstein here are my edits

 - Not sure if this is mean to be in the summary caption? 
image

-  Remove the 2nd program
image

- Links to VSFS here since it's the first time its mentioned 
image

- Suggestion to change "our website" to "ONRR's public website"
image

- Add data after disbursements. The last sentence needs more description, what are "these",  I suggest adding like "creating the yearly fact sheets"  or "creating the visuals for the renewable fact sheets" 
image


- Fix "akills" to "skills" mis-spelling in this paragraph heading title.  Also, link to our GitHub.
image

**Comment by Maroyafaied** [comment]
I'm not able to preview the blog using the preview link https://dev-blog-nrrd.app.cloud.gov/Matt-blog. I'll merge to dev to be able to review it.

**Pull request merged**
