### PR TITLE
plain-language-accessibility

### PR DESCRIPTION
**Pull request by cthomasONRR**
[Preview](https://dev-blog-nrrd.app.cloud.gov/plain-language-accessibility/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@lpgoldstein @AlexandracmONRR This blog is ready to review when yall have time. No rush!

**Comment by AlexandracmONRR** [comment]
I think this is supposed to be "through", but wanted to check!
image

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Great find! I didn't catch anything new. And neither did word when I put the blog back in there to read :( @cthomasONRR looks good other than Alex's catch.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - other than that one type-o question I had, everything else looks good!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR @lpgoldstein Thanks for reviewing. That typo is fixed.

**Review by AlexandracmONRR — APPROVED** [review]

**Pull request merged**
