### PR TITLE
Search Engine blog

### LINKED ISSUE #232: Create PR for search.gov blog

### PR DESCRIPTION
**Pull request by AlexandracmONRR**
Fixes #232 
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/search-engine/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@AlexandracmONRR 

"XML" needs to be capitalized in these locations, otherwise looks good! I tested all links, and they all work and direct as expected.

image

image

**Comment by AlexandracmONRR** [comment]
@cthomasONRR thanks Christine! I've made the requested changes!

**Comment by lpgoldstein** [comment]
@AlexandracmONRR Suggest a rewrite for this sentence - "Our developer at the time used this spreadsheet to upload **it** to our Content Management System (CMS) which integrates with our database." **"It"** is a little unclear to me. How about "Our developer at the time used this spreadsheet to upload the redirect links to our Content Management System (CMS) which integrates with our database"....or something similar? 
image

**Comment by lpgoldstein** [comment]
I would change all verbs to past tense here - "Search.gov instructed us to notify them when we launch the new website so they can replace the beta site domain with the new live site domain."
image

**Comment by lpgoldstein** [comment]
A word choice thing - take or leave it - change "would make for" to "would create" in "We initially thought that by adding as many of our URLs to the XML sitemap as possible, we would have a robust and complete sitemap that would make for an accurate search experience." And change "to verify" to "to be accepted" - 
image

**Comment by lpgoldstein** [comment]
I had to look up what canonical means in this case - 
image

**Comment by lpgoldstein** [comment]
@AlexandracmONRR @eelzi-ONRR @Maroyafaied This blog is awesome! As usual, I learned a ton and I think we will get a ton of views and shares.

**Review by cthomasONRR — APPROVED** [review]
@AlexandracmONRR Thanks for fixing. Approved!

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I'm good with Lindsay's changes on my sentences, I put a thumps up on those comments. I'll let @eelzi-ONRR look at the last suggestion for word change.

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - thank you - i just made those updates to the blog.

@eelzi-ONRR - the second comment of lindsay, I may need a bit more guidance on how to define canonical, which i looked up as "the best representative page for duplicate pages", but you may have a better way to define it for readers.

**Comment by eelzi-ONRR** [comment]
We can add this: "When Google recognizes duplicates of a page, it will prioritize the page marked as canonical in the results list".

Does that explain it well enough?

**Comment by AlexandracmONRR** [comment]
@lpgoldstein - incorporated your edits.

@eelzi-ONRR and @Maroyafaied - incorporated edits drafted by Erin.

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I reviewed and approved :) I will send the link to the public affairs manager to let him know we'll be publishing and sharing on the list servs. I'll include you in the email incase he has any changes.

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@AlexandracmONRR this is mis-spelled, it should be with an a instead of an o. Also, Chris will send us revisions in a word doc in a bit so you can wait to make the change until we get his changes. 
image

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - I've incorporated your edit and Chris M's edits into this most recent commit.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied Looks good! It's ready to merge :)

**Pull request merged**
