### PR TITLE
Added pricing tables blog and Isabel as an author

### PR DESCRIPTION
**Pull request by eelzi-ONRR**
[Preview](https://dev-blog-nrrd.app.cloud.gov/intern-pricing-tables/)

### CODE REVIEW

**Comment by lpgoldstein** [comment]
link doesn't fully cover word. image
small s 
image

**Comment by lpgoldstein** [comment]
small letters image

**Comment by lpgoldstein** [comment]
@eelzi-ONRR the main thing I found is to use sentence case for the titles - I didn't screenshot all of the instancews. I'm happy to make any edits as well. This looks great!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Great job! Here are my edits 

1. I'd suggest added "study" before plan and "guide" after interview in this sentence. 
image 
 
2. add "me" after helped and change is to are
image

3. Make the R lower case 
image

4. Can we link to USWDS and MUI 
image

5. Take the s out in "helps" and fix spelling for notetaker 
image

**Comment by eelzi-ONRR** [comment]
@Maroyafaied @cthomasONRR @lpgoldstein 

Thank you for your review! I made all those changes and a couple more that I found. Except for the one where Lindsay said the link doesnt; cover the entir word - it does, it's just the font that makes it look like it doesn't when g is at the start of the link

**Review by cthomasONRR — APPROVED** [review]
Looks great! Thanks for making updates. Approved!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR sorry I didn't catch this the first time but just a suggesting to say "interning" rather than "working' and maybe mention that the internship was through the[ virtual student federal service ](https://careers.state.gov/interns-fellows/virtual-student-federal-service/)program and link to it.  
image

**Comment by eelzi-ONRR** [comment]
@Maroyafaied No problem. I've made those changes

**Review by Maroyafaied — APPROVED** [review]

**Review by Maroyafaied — APPROVED** [review]

**Review by lpgoldstein — APPROVED** [review]

**Pull request merged**
