### PR TITLE
Metrics & Policy Blog

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<ISSUE NUMBER>
  
[Preview](https://dev-blog-nrrd.app.cloud.gov/metrics-and-policy/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@Maroyafaied 

I found the title a bit hard to read... what about something like "Maximizing impact of federal websites: integrating metrics with annual goals and policies"

Add a space here:
image

Add a space here:
image

Add commas here:
image

I still think it would be good to link to the wiki page (https://github.com/DOI-ONRR/nrrd/wiki/Goals-and-metrics) for the Key Metrics section... the tables in this section are are all duplicated from the wiki,

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I found a few punctuation, spacing, and grammatical errors. Sorry I missed these when I reviewed it in word - somethings pop-out more when they are in preview. Overall I love this post though!

- Remove the period at the end of the title

- Rearrange this sentence so it's not a dangling modifier and better refers to the aforementioned goals. Change to: "We focus our efforts on these top-priority annual goals by using a scale that considers both value and complexity guides us during roadmap planning sessions (every 6 weeks)." 
image

- Remove periods from these two list items: 
image


- Add colon after "2"
image

- Remove the second instance of "to" in this list: 
image

- Add a Space after the first Act and remove the second Act 
image

- Swap the order here, so it reads, "As of 2018, Section 508 adopted", and add commas after Guidelines) and after (W3C)
image

- Orienting words (above) are bad accessibility. I think you could just remove that entire part of the sentence. And remove the last part of the sentence. As it currently is I had to read this sentence 4 times and I think it's because that last part feels disconnected and repeats the first part in different words. Suggested sentence rewrite: We also follow DOI-specific Information Management Technology (IMT) strategic priorities which are aligned to the President’s Management Agenda (PMA), the [DOI FY 2022-2026 Strategic Plan](https://www.doi.gov/sites/doi.gov/files/u.s.-department-of-the-interior-fy-2022-2026-strategic-plan.pdf), the [DOI Information Resource Management (IRM) Strategic Plan](https://www.doi.gov/sites/doi.gov/files/uploads/doi-irm-2020-2025-strategic-plan.pdf), and the FY 2024–2029 IMT Strategic Plan (drafted for publication later this year).
image

- Change "above" to "in the previous section"
image

**Comment by AlexandracmONRR** [comment]
Hi - please see my edits below:

- change "we've" to "we".
image

- should change "quarter" to "quarter-"
image

- I think it could be useful to add the importance of including all team members on tracking metric. Consider this addition, but may need some editing "Including all team members to track at least one metric, promotes their buy-in to the metrics plan and encourages their input on the best ways to track the different metrics." You talk about this in lessons learned no. 4, but I wasn't sure if you want to mention it here too - it is okay if not.
image

- After lessons learned, I wonder if it would be useful/helpful to have a "Next Steps" section. It would only have to be a few sentences, but it could explain how the metrics will allow us to evaluate our team's against our goals. We may also decide that some of these metrics may not measure our work in the way we want, so we may remove them or change them. Finally, it will help us understand how and when we have achieved a goal and then it can shape our other goals in the future.

**Comment by Maroyafaied** [comment]
I believe I incorporated all the review comments except for taking out the table, @cthomasONRR I don't mind linking to the wiki but I'll ask Lindsay if she's ok with it since that was one of her sections in the blog. @AlexandracmONRR I like the next steps idea, just not sure how much I can write since we haven't evaluated the new metrics yet but I'll let you know if I decide to add this section to this blog or maybe it can be it's own blog as we work on metrics this year.

**Comment by Maroyafaied** [comment]
@lpgoldstein @AlexandracmONRR @cthomasONRR @eelzi-ONRR please review and approve if you don't have any further changes.  Lindsay linked to the wiki table and minor changes and I added a section for "next steps". Thanks

**Review by lpgoldstein — APPROVED** [review]

**Review by eelzi-ONRR — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@AlexandracmONRR I made the edits you suggested, please review. Thanks

**Comment by AlexandracmONRR** [comment]
Just one tiny edit - there should be a space after the comma here:

image

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Thanks, I made that change.

**Review by AlexandracmONRR — APPROVED** [review]

**Review by cthomasONRR — APPROVED** [review]
Looks good!

**Pull request merged**
