### PR TITLE
add-plain-language-blog

### PR DESCRIPTION
**Pull request by cthomasONRR**
[Preview](https://dev-blog-nrrd.app.cloud.gov/plain-language/)

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@Maroyafaied @lpgoldstein @AlexandracmONRR @eelzi-ONRR 

Hello, this blog post is ready for review. 

The images look small because of the page layout, but if you click on them they will open in a new window and be much bigger/easier to see.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - I reviewed and the content reads well and the links are all functioning!

Just as a general comment, is it possible to make all the linked text open in a new tab (rather than in the current tab)? This may be just a preference for me, but I always prefer a new tab so that I can continue reading in the current article that I'm in.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I just found this on Google. I'm gonna test with one link first to see if it works
image

**Comment by cthomasONRR** [comment]
First attempt did not work. Trying this instead: https://stackoverflow.com/questions/40026947/open-new-tab-on-link-markdown

image

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Using this raw html version works! It's going to take me a while to edit all the links, and the html is a bit more involved. I'll let you know when it's ready to review again.

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Yay! All links are updated to open in a new tab. I checked them all, and they're working for me, but please re-review. Thanks!

**Review by AlexandracmONRR — APPROVED** [review]
I re-checked the links and they all look good - I approve!

**Comment by Maroyafaied** [comment]
@cthomasONRR  Looks great, the only thing I noticed is in the "Final Design" heading, should "Design" be lower case for the title? 
image

**Review by lpgoldstein — APPROVED** [review]

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks for spotting that! It's fixed now:
image

**Review by Maroyafaied — APPROVED** [review]

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Thanks, this typo is corrected in the preview.

**Comment by Maroyafaied** [comment]
I'm merging to dev and going to create a dev to master PR.

**Pull request merged**
